[variables]
LD_LIBRARY_PATH = "/nix/store/*/lib:/run/current-system/sw/lib"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
CHROME_PATH = "/run/current-system/sw/bin/chromium"

[phases.setup]
nixPkgs = [
  "chromium",
  "glib",
  "nss",
  "nspr",
  "atk",
  "cups",
  "libdrm",
  "dbus",
  "libxkbcommon",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "xorg.libxcb",
  "xorg.libX11",
  "xorg.libXext",
  "mesa",
  "pango",
  "cairo",
  "alsa-lib",
  "expat",
  "fontconfig",
  "freetype",
  "gdk-pixbuf",
  "gtk3",
  "at-spi2-atk",
  "at-spi2-core",
]

[phases.build]
cmds = ["npm install"]

[phases.start]
cmd = "node server.js"
